import type * as THREE from 'three';
import type { Grid3D, BoundaryMode } from '../sim/grid';
import type { Rule } from '../sim/rules';
import type { SymmetryMode } from '../sim/symmetry';
import type { AppSnapshot } from '../sim/share';
import type { GenesisScene } from '../render/scene';
import type { VoxelRenderer } from '../render/voxels';
import type { TrailRenderer } from '../render/trails';
import type { SlicePlane, SliceAxis } from '../render/slice';
import type { CameraPresetId } from '../render/camera';

export type InteractionMode = 'orbit' | 'paint';

/** Surface used by UI/input binders (avoids circular imports). */
export interface AppHost {
  scene: GenesisScene;
  voxels: VoxelRenderer;
  trails: TrailRenderer;
  slice: SlicePlane;
  grid: Grid3D;
  scratch: Grid3D;
  rule: Rule;
  boundary: BoundaryMode;
  generation: number;
  playing: boolean;
  speed: number;
  density: number;
  seedName: string;
  seedId: string;
  accum: number;
  raycaster: THREE.Raycaster;
  pointer: THREE.Vector2;
  painting: boolean;
  paintErase: boolean;
  reducedMotion: boolean;
  trailsEnabled: boolean;
  toastTimer: number;
  symmetry: SymmetryMode;
  brushRadius: number;
  interactionMode: InteractionMode;
  lastPaintKey: string;
  fillPresetSelects(): void;
  refreshLocalizedUI(): void;
  updateRuleDesc(): void;
  updateSeedDesc(): void;
  loadSnapshot(snap: AppSnapshot): void;
  makeSnapshot(): AppSnapshot;
  goCamera(id: CameraPresetId): void;
  setInteractionMode(mode: InteractionMode): void;
  applyInteractionMode(): void;
  updatePointer(e: PointerEvent, canvas: HTMLCanvasElement): void;
  paintAt(x: number, y: number, z: number): void;
  updatePaintCoordHud(x: number, y: number, z: number): void;
  clickAxis(axis: SliceAxis): void;
  toggleSlice(): void;
  nudgeSlice(d: number): void;
  togglePlay(): void;
  doStep(): void;
  reset(): void;
  plantSeed(id: string): void;
  randomize(): void;
  resizeWorld(size: number): void;
  exportJSON(): void;
  syncUI(): void;
  syncStats(): void;
  showFirstHint(): void;
  dismissHint(): void;
  toast(msg: string): void;
  displaySeedName(): string;
}
