import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const partsDir = path.join(root, "src/app.parts");
const out = path.join(root, "src/app.ts");
const files = fs.readdirSync(partsDir).filter((f) => f.endsWith(".ts.txt")).sort();
const content = files.map((f) => fs.readFileSync(path.join(partsDir, f), "utf8")).join("");
fs.writeFileSync(out, content);
console.log("assembled", out, content.length, "from", files.join(","));
